version: '3.9'

services:
  db:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./db/data:/data/db"
    ports:
      - "27017:27017"
#    command:
#      - None

  generator_service:
    build: .
    container_name: header_generator
    image: python:3.6-alpine
    environment:
      DB_HOST: db
      DB_PORT: 27017
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: mongo_db
    ports:
      - "8050:8050"
    depends_on:
      - db
